### ISSUE TITLE
running the script gives error

### ISSUE THREAD

**Issue by naseemr** [jlefler/ZoneminderEmail#1]
I get the following error:
File "zmEmail.py", line 1, in <module>
    import daemon
  File "/usr/local/lib/python3.5/dist-packages/daemon.py", line 70
    os.umask(022)   # Don't allow others to write
               ^
SyntaxError: invalid token

**Comment by jlefler** [comment]
It looks like you're trying to run zmEmail with Python3. I wrote it with Python 2 and I don't believe it is 3 compatible at this time. To verify, run python -v
